# WhatsApp to Zoom Automator Configuration

browser:
  cdp_url: "http://localhost:9222"
  timeout: 30000

whatsapp:
  target_chat: "Your Chat Name" # Name of the chat/group to monitor  --BSIT23-27 M 6TH S WITH HOD
  poll_interval: 1.0 # Seconds to wait in the main loop

output:
  links_file: "found_zoom_links.txt" # Where to save all matched meetings

name:
  display_name: "Your Name" # Your name here to use when joining meetings
zoom:
  auto_join: true # If true, the bot will automatically open a new tab and launch the meeting

meet:
  auto_join: true # If true, the bot will automatically join identified Google Meet links

logging:
  level: "INFO"
  file: "automator.log"
